### ISSUE TITLE
Hubspot returns a 414 when requesting a large property set

### ISSUE THREAD

**Issue by irenegonzalez27** [potloc/tap-hubspot#93]
All properties for a given object are requested from Hubspot, regardless of what the select config is. For objects with a large set of properties, this yields a 414.

**Comment by SBurwash** [comment]
Hey @irenegonzalez27 👋 we have merged your PR which addressed this issue (see https://github.com/potloc/tap-hubspot/releases/tag/1.3.0)

We will be closing this issue.
